import type { CategoryData, Category } from './repository-categories';
// Public GitHub sources fetched 2026-09-05T11:16:36.211Z; retained as labelled offline snapshots.
export const CATEGORY_SEED: Record<Category, CategoryData> = {
  top: {
    repositories: [
      {
        fullName: 'codecrafters-io/build-your-own-x',
        name: 'build-your-own-x',
        description:
          'Master programming by recreating your favorite technologies from scratch.',
        stars: 545324,
        language: 'Markdown',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'sindresorhus/awesome',
        name: 'awesome',
        description:
          '😎 Awesome lists about all kinds of interesting topics [NOTE: Pull requests are temporarily disabled until I have a chance to catch up with the existing ones]',
        stars: 503144,
        language: null,
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'public-apis/public-apis',
        name: 'public-apis',
        description: 'A collective list of free APIs',
        stars: 475580,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'freeCodeCamp/freeCodeCamp',
        name: 'freeCodeCamp',
        description:
          "freeCodeCamp.org's open-source codebase and curriculum. Learn math, programming, and computer science for free.",
        stars: 455034,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'EbookFoundation/free-programming-books',
        name: 'free-programming-books',
        description: ':books: Freely available programming books',
        stars: 396006,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'openclaw/openclaw',
        name: 'openclaw',
        description:
          'The AI that really does things. Any OS. Any Platform. The lobster way. 🦞 ',
        stars: 388921,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'donnemartin/system-design-primer',
        name: 'system-design-primer',
        description:
          'Learn how to design large-scale systems. Prep for the system design interview.  Includes Anki flashcards.',
        stars: 368038,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#b29165',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'nilbuild/developer-roadmap',
        name: 'developer-roadmap',
        description:
          'Interactive roadmaps, guides and other educational content to help developers grow in their careers.',
        stars: 366337,
        language: 'TypeScript',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#b29165',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'jwasham/coding-interview-university',
        name: 'coding-interview-university',
        description:
          'A complete computer science study plan to become a software engineer.',
        stars: 360380,
        language: null,
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'vinta/awesome-python',
        name: 'awesome-python',
        description:
          'The definitive list that answers "I want to do X in Python, which tool should I use?"',
        stars: 318357,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'awesome-selfhosted/awesome-selfhosted',
        name: 'awesome-selfhosted',
        description:
          'A list of Free Software network services and web applications which can be hosted on your own servers',
        stars: 317251,
        language: null,
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#b29165',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'practical-tutorials/project-based-learning',
        name: 'project-based-learning',
        description: 'Curated list of project-based tutorials',
        stars: 282137,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'obra/superpowers',
        name: 'superpowers',
        description:
          'An agentic skills framework & software development methodology that works.',
        stars: 281933,
        language: 'Shell',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: '996icu/996.ICU',
        name: '996.ICU',
        description:
          'Repo for counting stars and contributing. Press F to pay respect to glorious developers.',
        stars: 276884,
        language: null,
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'mattpocock/skills',
        name: 'skills',
        description:
          'Skills for Real Engineers. Straight from my .agents directory.',
        stars: 251356,
        language: 'Shell',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'react/react',
        name: 'react',
        description: 'The library for web and native user interfaces.',
        stars: 249082,
        language: 'JavaScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'affaan-m/ECC',
        name: 'ECC',
        description:
          'The agent harness performance optimization system. Skills, instincts, memory, security, and research-first development for Claude Code, Codex, Opencode, Cursor and beyond.',
        stars: 248987,
        language: 'JavaScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'torvalds/linux',
        name: 'linux',
        description: 'Linux kernel source tree',
        stars: 246679,
        language: 'C',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'trimstray/the-book-of-secret-knowledge',
        name: 'the-book-of-secret-knowledge',
        description:
          'A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools and more.',
        stars: 242146,
        language: null,
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'NousResearch/hermes-agent',
        name: 'hermes-agent',
        description: 'The agent that grows with you',
        stars: 241719,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'TheAlgorithms/Python',
        name: 'Python',
        description: 'All Algorithms implemented in Python',
        stars: 224272,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'deepseek-ai/deepseek-harness',
        name: 'deepseek-harness',
        description: 'DeepSeek Harness: Everything is a Plugin.',
        stars: 212751,
        language: 'TypeScript',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'vuejs/vue',
        name: 'vue',
        description:
          'This is the repo for Vue 2. For Vue 3, go to https://github.com/vuejs/core',
        stars: 211626,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'multica-ai/andrej-karpathy-skills',
        name: 'andrej-karpathy-skills',
        description:
          "A single CLAUDE.md file to improve Claude Code behavior, derived from Andrej Karpathy's observations on LLM coding pitfalls.",
        stars: 210256,
        language: null,
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'ossu/computer-science',
        name: 'computer-science',
        description:
          '🎓 Path to a free self-taught education in Computer Science!',
        stars: 208731,
        language: 'HTML',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'anomalyco/opencode',
        name: 'opencode',
        description: 'The open source coding agent.',
        stars: 204391,
        language: 'TypeScript',
        defaultBranch: 'dev',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'n8n-io/n8n',
        name: 'n8n',
        description:
          'Fair-code workflow automation platform with native AI capabilities. Combine visual building with custom code, self-host or cloud, 400+ integrations.',
        stars: 203416,
        language: 'TypeScript',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'tensorflow/tensorflow',
        name: 'tensorflow',
        description: 'An Open Source Machine Learning Framework for Everyone',
        stars: 198839,
        language: 'C++',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'DigitalPlatDev/FreeDomain',
        name: 'FreeDomain',
        description:
          'Free domain registration and practical DNS learning resources for everyone.',
        stars: 197662,
        language: 'Markdown',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'trekhleb/javascript-algorithms',
        name: 'javascript-algorithms',
        description:
          '📝 Algorithms and data structures implemented in JavaScript with explanations and links to further readings',
        stars: 196616,
        language: 'JavaScript',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'ultraworkers/claw-code',
        name: 'claw-code',
        description:
          'An agent-managed museum exhibit, built in Rust with Gajae-Code / LazyCodex — developed and maintained with no human intervention.',
        stars: 195170,
        language: 'Rust',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'microsoft/vscode',
        name: 'vscode',
        description: 'Visual Studio Code',
        stars: 190881,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'ohmyzsh/ohmyzsh',
        name: 'ohmyzsh',
        description:
          '🙃   A delightful community-driven (with 2,500+ contributors) framework for managing your zsh configuration. Includes 300+ optional plugins (rails, git, macOS, hub, docker, homebrew, node, php, python, etc), 140+ themes to spice up your mor',
        stars: 189550,
        language: 'Shell',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'massgravel/Microsoft-Activation-Scripts',
        name: 'Microsoft-Activation-Scripts',
        description:
          'Open-source Windows and Office activator featuring HWID, Ohook, TSforge, and Online KMS activation methods, along with advanced troubleshooting.',
        stars: 189429,
        language: 'Batchfile',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'yt-dlp/yt-dlp',
        name: 'yt-dlp',
        description: 'A feature-rich command-line audio/video downloader',
        stars: 189092,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'Significant-Gravitas/AutoGPT',
        name: 'AutoGPT',
        description:
          'AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools, so that you can focus on what matters.',
        stars: 187140,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#b29165',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'jackfrued/Python-100-Days',
        name: 'Python-100-Days',
        description: 'Python - 100天从新手到大师',
        stars: 185949,
        language: 'Jupyter Notebook',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'CyC2018/CS-Notes',
        name: 'CS-Notes',
        description:
          ':books: 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计',
        stars: 185828,
        language: null,
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#96624c',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'getify/You-Dont-Know-JS',
        name: 'You-Dont-Know-JS',
        description: 'A book series (2 published editions) on the JS language.',
        stars: 184808,
        language: null,
        defaultBranch: '2nd-ed',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'avelino/awesome-go',
        name: 'awesome-go',
        description:
          'A curated list of awesome Go frameworks, libraries and software',
        stars: 183194,
        language: 'Go',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'ollama/ollama',
        name: 'ollama',
        description:
          'Get up and running with Kimi-K2.6, GLM-5.2, MiniMax, DeepSeek, gpt-oss, Qwen, Gemma and other models.',
        stars: 180203,
        language: 'Go',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'flutter/flutter',
        name: 'flutter',
        description:
          'Flutter makes it easy and fast to build beautiful apps for mobile and beyond',
        stars: 178780,
        language: 'Dart',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'microsoft/markitdown',
        name: 'markitdown',
        description:
          'Python tool for converting files and office documents to Markdown.',
        stars: 178252,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'firecrawl/firecrawl',
        name: 'firecrawl',
        description:
          'The context API to search, scrape, and interact with the web at scale. 🔥',
        stars: 176693,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#b29165',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'github/gitignore',
        name: 'gitignore',
        description: 'A collection of useful .gitignore templates',
        stars: 175603,
        language: null,
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: '521xueweihan/HelloGitHub',
        name: 'HelloGitHub',
        description:
          ':octocat: 分享 GitHub 上有趣、入门级的开源项目。Share interesting, entry-level open source projects on GitHub.',
        stars: 174824,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'twbs/bootstrap',
        name: 'bootstrap',
        description:
          'The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.',
        stars: 174719,
        language: 'MDX',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'anthropics/skills',
        name: 'skills',
        description: 'Public repository for Agent Skills',
        stars: 174336,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'f/prompts.chat',
        name: 'prompts.chat',
        description:
          'f.k.a. Awesome ChatGPT Prompts. Share, discover, and collect prompts from the community. Free and open source — self-host for your organization with complete privacy.',
        stars: 169369,
        language: 'HTML',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'AUTOMATIC1111/stable-diffusion-webui',
        name: 'stable-diffusion-webui',
        description: 'Stable Diffusion web UI',
        stars: 164822,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'huggingface/transformers',
        name: 'transformers',
        description:
          '🤗 Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, for both inference and training. ',
        stars: 164809,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'jlevy/the-art-of-command-line',
        name: 'the-art-of-command-line',
        description: 'Master the command line, in one page',
        stars: 162248,
        language: null,
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'Snailclimb/JavaGuide',
        name: 'JavaGuide',
        description:
          'Java 面试 & 后端通用面试指南，覆盖计算机基础、数据库、分布式、高并发、系统设计与 AI 应用开发',
        stars: 158282,
        language: 'JavaScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'langgenius/dify',
        name: 'dify',
        description:
          'Build Agentic workflows, RAG pipelines, with rich AI model and tool support on one collaborative workspace. Deploy on cloud, VPC, or self-hosted, so teams move from prototype to production without rebuilding the stack.',
        stars: 154497,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#96624c',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'langflow-ai/langflow',
        name: 'langflow',
        description:
          'Langflow is a powerful tool for building and deploying AI-powered agents and workflows.',
        stars: 154273,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'open-webui/open-webui',
        name: 'open-webui',
        description:
          'User-friendly AI Interface (Supports Ollama, OpenAI API, ...)',
        stars: 150997,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'msitarzewski/agency-agents',
        name: 'agency-agents',
        description:
          'A complete AI agency at your fingertips - From frontend wizards to Reddit community ninjas, from whimsy injectors to reality checkers. Each agent is a specialized expert with personality, processes, and proven deliverables.',
        stars: 150167,
        language: 'Shell',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'Genymobile/scrcpy',
        name: 'scrcpy',
        description: 'Display and control your Android device',
        stars: 148929,
        language: 'C',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'airbnb/javascript',
        name: 'javascript',
        description: 'JavaScript Style Guide',
        stars: 148151,
        language: 'JavaScript',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'langchain-ai/langchain',
        name: 'langchain',
        description: 'The agent engineering platform.',
        stars: 145682,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'anthropics/claude-code',
        name: 'claude-code',
        description:
          'Claude Code is an agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster by executing routine tasks, explaining complex code, and handling git workflows - all through natural language commands.',
        stars: 144125,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#96624c',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'x1xhlol/system-prompts-and-models-of-ai-tools',
        name: 'system-prompts-and-models-of-ai-tools',
        description:
          'FULL Augment Code, Claude Code, Cluely, CodeBuddy, Comet, Cursor, Devin AI, Junie, Kiro, Leap.new, Lovable, Manus, NotionAI, Orchids.app, Perplexity, Poke, Qoder, Replit, Same.dev, Trae, Traycer AI, VSCode Agent, Warp.dev, Windsurf, Xcode, ',
        stars: 143369,
        language: null,
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'yangshun/tech-interview-handbook',
        name: 'tech-interview-handbook',
        description:
          'Curated coding interview preparation materials for busy software engineers',
        stars: 142438,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'clash-verge-rev/clash-verge-rev',
        name: 'clash-verge-rev',
        description:
          'A modern GUI client based on Tauri, designed to run in Windows, macOS and Linux for tailored proxy experience',
        stars: 142363,
        language: 'TypeScript',
        defaultBranch: 'dev',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'vercel/next.js',
        name: 'next.js',
        description: 'The React Framework',
        stars: 142098,
        language: 'JavaScript',
        defaultBranch: 'canary',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'ytdl-org/youtube-dl',
        name: 'youtube-dl',
        description:
          'Command-line program to download videos from YouTube.com and other video sites',
        stars: 141114,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'microsoft/PowerToys',
        name: 'PowerToys',
        description:
          'Microsoft PowerToys is a collection of utilities that supercharge productivity and customization on Windows',
        stars: 138406,
        language: 'C',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'iptv-org/iptv',
        name: 'iptv',
        description:
          'Collection of publicly available IPTV channels from all over the world',
        stars: 137665,
        language: 'TypeScript',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'golang/go',
        name: 'go',
        description: 'The Go programming language',
        stars: 137515,
        language: 'Go',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'ripienaar/free-for-dev',
        name: 'free-for-dev',
        description:
          'A list of SaaS, PaaS and IaaS offerings that have free tiers of interest to devops and infradev',
        stars: 136596,
        language: 'HTML',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#96624c',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'Shubhamsaboo/awesome-llm-apps',
        name: 'awesome-llm-apps',
        description:
          '100+ AI Agents, Agent Skills and RAG Apps - Free and Open Source.',
        stars: 136123,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'labuladong/fucking-algorithm',
        name: 'fucking-algorithm',
        description: 'Crack LeetCode, not only how, but also why. ',
        stars: 135637,
        language: 'Markdown',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#b29165',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'github/spec-kit',
        name: 'spec-kit',
        description:
          '💫 Toolkit to help you get started with Spec-Driven Development',
        stars: 133552,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'Comfy-Org/ComfyUI',
        name: 'ComfyUI',
        description:
          'The most powerful and modular diffusion model GUI, api and backend with a graph/nodes interface.',
        stars: 131580,
        language: 'Python',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'garrytan/gstack',
        name: 'gstack',
        description:
          "Use Garry Tan's exact Claude Code setup: 23 opinionated tools that serve as CEO, Designer, Eng Manager, Release Manager, Doc Engineer, and QA",
        stars: 131426,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'excalidraw/excalidraw',
        name: 'excalidraw',
        description:
          'Virtual whiteboard for sketching hand-drawn like diagrams',
        stars: 131186,
        language: 'TypeScript',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'farion1231/cc-switch',
        name: 'cc-switch',
        description:
          'A cross-platform desktop All-in-One assistant for Claude Code, Codex, OpenCode, OpenClaw, Grok Build & Hermes Agent. Only official website: ccswitch.io',
        stars: 131152,
        language: 'Rust',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'krahets/hello-algo',
        name: 'hello-algo',
        description:
          '《Hello 算法》：动画图解、一键运行的数据结构与算法教程。支持简中、繁中、English、日本語，提供 Python, Java, C++, C, C#, JS, Go, Swift, Rust, Ruby, Kotlin, TS, Dart 等代码实现',
        stars: 129877,
        language: 'Java',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'Chalarangelo/30-seconds-of-code',
        name: '30-seconds-of-code',
        description: 'Coding articles to level up your development skills',
        stars: 128953,
        language: 'JavaScript',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'ggml-org/llama.cpp',
        name: 'llama.cpp',
        description: 'LLM inference in C/C++',
        stars: 127113,
        language: 'C++',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'DietrichGebert/ponytail',
        name: 'ponytail',
        description:
          'Makes your AI agent think like the laziest senior dev in the room. The best code is the code you never wrote.',
        stars: 127080,
        language: 'JavaScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'react/react-native',
        name: 'react-native',
        description: 'A framework for building native applications using React',
        stars: 126502,
        language: 'C++',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'kubernetes/kubernetes',
        name: 'kubernetes',
        description: 'Production-Grade Container Scheduling and Management',
        stars: 126368,
        language: 'Go',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'nextlevelbuilder/ui-ux-pro-max-skill',
        name: 'ui-ux-pro-max-skill',
        description:
          'An AI skill that provides design intelligence for building professional UI/UX across multiple platforms.',
        stars: 125132,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'shadcn-ui/ui',
        name: 'ui',
        description:
          'A set of beautifully-designed, accessible components and a code distribution platform. Works with your favorite frameworks. Open Source. Open Code.',
        stars: 123067,
        language: 'TypeScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'electron/electron',
        name: 'electron',
        description:
          ':electron: Build cross-platform desktop apps with JavaScript, HTML, and CSS',
        stars: 122886,
        language: 'C++',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'rustdesk/rustdesk',
        name: 'rustdesk',
        description:
          'An open-source remote desktop application designed for self-hosting, as an alternative to TeamViewer.',
        stars: 122654,
        language: 'Rust',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'openai/codex',
        name: 'codex',
        description: 'Lightweight coding agent that runs in your terminal',
        stars: 121647,
        language: 'Rust',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'harry0703/MoneyPrinterTurbo',
        name: 'MoneyPrinterTurbo',
        description:
          '利用 AI 大模型和自动化工作流，根据主题或关键词一键生成高清短视频。Generate HD short videos from a topic or keyword with an automated AI workflow.',
        stars: 120752,
        language: 'Python',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'nodejs/node',
        name: 'node',
        description: 'Node.js JavaScript runtime ✨🐢🚀✨',
        stars: 120628,
        language: 'JavaScript',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'Hack-with-Github/Awesome-Hacking',
        name: 'Awesome-Hacking',
        description:
          'A collection of various awesome lists for hackers, pentesters and security researchers',
        stars: 119721,
        language: null,
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'microsoft/generative-ai-for-beginners',
        name: 'generative-ai-for-beginners',
        description: '21 Lessons, Get Started Building with Generative AI ',
        stars: 119187,
        language: 'Jupyter Notebook',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'justjavac/free-programming-books-zh_CN',
        name: 'free-programming-books-zh_CN',
        description: ':books: 免费的计算机编程类中文书籍，欢迎投稿',
        stars: 118684,
        language: null,
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'rust-lang/rust',
        name: 'rust',
        description:
          'Empowering everyone to build reliable and efficient software.',
        stars: 117456,
        language: 'Rust',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'godotengine/godot',
        name: 'godot',
        description: 'Godot Engine – Multi-platform 2D and 3D game engine',
        stars: 116621,
        language: 'C++',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#7d9193',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: '2dust/v2rayN',
        name: 'v2rayN',
        description:
          'A GUI client for Windows, Linux and macOS, support Xray and sing-box and others',
        stars: 115471,
        language: 'C#',
        defaultBranch: 'master',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'mrdoob/three.js',
        name: 'three.js',
        description: 'JavaScript 3D Library.',
        stars: 115136,
        language: 'JavaScript',
        defaultBranch: 'dev',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'Graphify-Labs/graphify',
        name: 'graphify',
        description:
          'Turn any codebase, with its docs, SQL schemas, configs, and PDFs, into a queryable knowledge graph. A /graphify skill for Claude Code, Cursor, Codex, and Gemini CLI: local deterministic AST parsing, every edge explained, no vector store.',
        stars: 114884,
        language: 'Python',
        defaultBranch: 'v8',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'VoltAgent/awesome-design-md',
        name: 'awesome-design-md',
        description:
          'A collection of DESIGN.md files analysis by popular brand design systems. Drop one into your project and let coding agents generate a matching UI.',
        stars: 114193,
        language: null,
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#b29165',
          roof: 'gable',
        },
        configStatus: 'unavailable',
      },
      {
        fullName: 'd3/d3',
        name: 'd3',
        description:
          'Bring data to life with SVG, Canvas and HTML. :bar_chart::chart_with_upwards_trend::tada:',
        stars: 113627,
        language: 'Shell',
        defaultBranch: 'main',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
      },
    ],
    refreshedAt: 1788606996211,
  },
  trending: {
    repositories: [
      {
        fullName: 'tt-a1i/archify',
        name: 'archify',
        description:
          'Agent skill for beautiful, verifiable architecture, workflow, sequence, data-flow, and lifecycle diagrams—self-contained HTML with motion and crisp export.',
        stars: 48723,
        language: 'JavaScript',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#778565',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 21896,
      },
      {
        fullName: 'THU-MAIC/OpenMAIC',
        name: 'OpenMAIC',
        description:
          'Open Multi-Agent Interactive Classroom — Get an immersive, multi-agent learning experience in just one click',
        stars: 31703,
        language: 'TypeScript',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#b29165',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 10274,
      },
      {
        fullName: 'Gitlawb/openclaude',
        name: 'openclaude',
        description: 'runs anywhere. uses anything',
        stars: 32645,
        language: 'TypeScript',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#96624c',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 1679,
      },
      {
        fullName: 'google-research/timesfm',
        name: 'timesfm',
        description:
          'TimesFM (Time Series Foundation Model) is a pretrained time-series foundation model developed by Google Research for time-series forecasting.',
        stars: 31195,
        language: 'Python',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 2653,
      },
      {
        fullName: 'jingyaogong/minimind',
        name: 'minimind',
        description: '🧠 Train a 64M-parameter LLM from scratch in just 2h!',
        stars: 58657,
        language: 'Python',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 3390,
      },
      {
        fullName: 'tailscale/tailcat',
        name: 'tailcat',
        description:
          "like netcat, but over Tailscale's data plane, without Tailscale's control plane",
        stars: 6288,
        language: 'Go',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 3762,
      },
      {
        fullName: 'K-Dense-AI/scientific-agent-skills',
        name: 'scientific-agent-skills',
        description:
          'Turn any AI agent into an AI Scientist. The #1 Agent Skills library for science, used by 190,000+ scientists worldwide. 165 ready-to-use validated skills plus 100+ scientific databases covering biology, chemistry, medicine, and drug discove',
        stars: 42789,
        language: 'Python',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#899080',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 6898,
      },
      {
        fullName: 'Lakr233/vphone-cli',
        name: 'vphone-cli',
        description: '',
        stars: 10627,
        language: 'Swift',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 1982,
      },
      {
        fullName: 'fmtlib/fmt',
        name: 'fmt',
        description: 'A modern formatting library',
        stars: 25523,
        language: 'C++',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#8c704a',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 1671,
      },
      {
        fullName: 'handsomestWei/patent-disclosure-skill',
        name: 'patent-disclosure-skill',
        description:
          '中国专利.skill：专利点挖掘与交底书（发明/实用/外观）编写，通俗解读专利，嗅探政策动向，辅助审查答复。',
        stars: 7430,
        language: 'Python',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#b29165',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 1975,
      },
      {
        fullName: 'debpalash/VoiceStudio',
        name: 'VoiceStudio',
        description:
          'VoiceStudio is the open-source, fully-local ElevenLabs alternative — voice cloning, voice design, video dubbing, dictation, transcription & audiobook creation in 646 languages.',
        stars: 18523,
        language: 'Python',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 5150,
      },
      {
        fullName: 'magnitudedev/magnitude',
        name: 'magnitude',
        description:
          'Open source inference server that runs the best local models for your hardware, plugged into the agent you already use. Works with Pi, OpenCode, Hermes, OpenClaw, Codex, Claude Code, Oh My Pi, and Cline.',
        stars: 2799,
        language: 'TypeScript',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#96624c',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 740,
      },
      {
        fullName: 'every-app/open-seo',
        name: 'open-seo',
        description: 'Open source alternative to Semrush and Ahrefs',
        stars: 17155,
        language: 'TypeScript',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'stone',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 2950,
      },
      {
        fullName: 'bilawalsidhu/gods-eye-view',
        name: 'gods-eye-view',
        description:
          'A spy satellite simulator in your browser, except the data is real. Live open source spatial intelligence on a photorealistic 3D globe.',
        stars: 17755,
        language: 'JavaScript',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 7314,
      },
      {
        fullName: 'punkpeye/awesome-mcp-servers',
        name: 'awesome-mcp-servers',
        description: 'A collection of MCP servers.',
        stars: 94240,
        language: null,
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 1198,
      },
      {
        fullName: 'p-e-w/heretic',
        name: 'heretic',
        description: 'Fully automatic censorship removal for language models',
        stars: 30511,
        language: 'Python',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#96624c',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 2065,
      },
      {
        fullName: 'majd/ipatool',
        name: 'ipatool',
        description:
          'Command-line tool that allows searching and downloading app packages (known as ipa files) for iOS, iPadOS, tvOS, and visionOS from the App Store.',
        stars: 10894,
        language: 'Go',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 903,
      },
      {
        fullName: 'affaan-m/ECC',
        name: 'ECC',
        description:
          'The agent harness performance optimization system. Skills, instincts, memory, security, and research-first development for Claude Code, Codex, Opencode, Cursor and beyond.',
        stars: 248988,
        language: 'JavaScript',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'townhouse',
          color: '#8c704a',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 4815,
      },
      {
        fullName: 'ChromeDevTools/chrome-devtools-mcp',
        name: 'chrome-devtools-mcp',
        description: 'Chrome DevTools for coding agents',
        stars: 50982,
        language: 'TypeScript',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'greenhouse',
          color: '#778565',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 1067,
      },
      {
        fullName: 'checkstyle/checkstyle',
        name: 'checkstyle',
        description:
          'Checkstyle is a development tool to help programmers write Java code that adheres to a coding standard. By default it supports the Google Java Style Guide and Sun Code Conventions, but is highly configurable. It can be invoked with an ANT t',
        stars: 9530,
        language: 'Java',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'woodland',
          color: '#899080',
          roof: 'flat',
        },
        configStatus: 'unavailable',
        weeklyStars: 569,
      },
      {
        fullName: 'abi/screenshot-to-code',
        name: 'screenshot-to-code',
        description:
          'Drop in a screenshot and convert it to clean code (HTML/Tailwind/React/Vue)',
        stars: 77787,
        language: 'Python',
        defaultBranch: 'HEAD',
        fetchedAt: 1788606996211,
        building: {
          version: 1,
          style: 'brick',
          color: '#7d9193',
          roof: 'gable',
        },
        configStatus: 'unavailable',
        weeklyStars: 2372,
      },
    ],
    refreshedAt: 1788606996211,
  },
  community: {
    repositories: [],
    refreshedAt: 0,
  },
  sponsored: {
    repositories: [],
    refreshedAt: 0,
  },
};
