import { defaultBuilding, type Repository } from './repositories';

// Public GitHub REST metadata verified 2026-09-05. A labelled fallback,
// not fabricated sample counts; the shared endpoint refreshes this snapshot.
const snapshot: [string, number, string, string, string][] = [
  [
    'react/react',
    249082,
    'JavaScript',
    'main',
    'The library for web and native user interfaces.',
  ],
  [
    'vuejs/core',
    54302,
    'TypeScript',
    'main',
    'Vue.js is a progressive JavaScript framework for building UI on the web.',
  ],
  [
    'sveltejs/svelte',
    88038,
    'JavaScript',
    'main',
    'Web development for the rest of us.',
  ],
  ['mrdoob/three.js', 115135, 'JavaScript', 'dev', 'JavaScript 3D Library.'],
  [
    'vitejs/vite',
    82687,
    'TypeScript',
    'main',
    'Next generation frontend tooling.',
  ],
  [
    'withastro/astro',
    62311,
    'TypeScript',
    'main',
    'The web framework for content-driven websites.',
  ],
  ['vercel/next.js', 142097, 'JavaScript', 'canary', 'The React Framework.'],
  [
    'denoland/deno',
    108371,
    'Rust',
    'main',
    'A modern runtime for JavaScript and TypeScript.',
  ],
  [
    'oven-sh/bun',
    95887,
    'Rust',
    'main',
    'JavaScript runtime, bundler, test runner, and package manager.',
  ],
  ['nodejs/node', 120628, 'JavaScript', 'main', 'Node.js JavaScript runtime.'],
  [
    'tailwindlabs/tailwindcss',
    97442,
    'TypeScript',
    'main',
    'A utility-first CSS framework for rapid UI development.',
  ],
  [
    'godotengine/godot',
    116619,
    'C++',
    'master',
    'Multi-platform 2D and 3D game engine.',
  ],
  [
    'excalidraw/excalidraw',
    131187,
    'TypeScript',
    'master',
    'Virtual whiteboard for sketching hand-drawn-like diagrams.',
  ],
  ['blender/blender', 20003, 'C++', 'main', 'Official mirror of Blender.'],
  [
    'rust-lang/rust',
    117456,
    'Rust',
    'main',
    'Empowering everyone to build reliable and efficient software.',
  ],
  [
    'python/cpython',
    75983,
    'Python',
    'main',
    'The Python programming language.',
  ],
  ['golang/go', 137515, 'Go', 'master', 'The Go programming language.'],
  [
    'microsoft/TypeScript',
    110896,
    'Go',
    'main',
    'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.',
  ],
  [
    'neovim/neovim',
    102133,
    'Vim Script',
    'master',
    'Vim-fork focused on extensibility and usability.',
  ],
  [
    'helix-editor/helix',
    46087,
    'Rust',
    'master',
    'A post-modern modal text editor.',
  ],
  [
    'zed-industries/zed',
    89790,
    'Rust',
    'main',
    'A high-performance, multiplayer code editor.',
  ],
  ['jqlang/jq', 35552, 'C', 'master', 'Command-line JSON processor.'],
  ['sharkdp/bat', 60372, 'Rust', 'master', 'A cat(1) clone with wings.'],
  [
    'sharkdp/fd',
    44313,
    'Rust',
    'master',
    'A simple, fast and user-friendly alternative to find.',
  ],
];
export const REPOSITORY_SEED: Repository[] = snapshot.map(
  ([fullName, stars, language, defaultBranch, description]) => ({
    fullName,
    name: fullName.split('/')[1],
    stars,
    language,
    defaultBranch,
    description,
    fetchedAt: 1788605130508,
    building: defaultBuilding(fullName.length),
    configStatus: 'unavailable',
  }),
);
